[theme]
base = "dark"
primaryColor = "#E694FF"
backgroundColor = "#420171"
secondaryBackgroundColor = "#310452"
textColor = "#DCDCDC"
font = "sans-serif"
[deprecation]
showfileUploaderEncoding = false
[general]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "foxway2023"

